/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.PMS;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author siddharth thakur
 */
public class Selection extends javax.swing.JFrame {

    /**
     * Creates new form Selection
     */
     String em;
    String na;
    public Selection() {
        initComponents();
        ImageIcon icon=new ImageIcon("Images/parking.png");
        Labelpic.setIcon(icon);
        updateTable();
        
        
    }
public void updateTable()
{
        try{ 
    Class.forName("com.mysql.jdbc.Driver"); 
     
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root","siddharth"); 
     
    //here sonoo is database name, root is username and password 
     
    Statement stmt=con.createStatement(); 
     
    ResultSet rs=stmt.executeQuery("select * from parking"); 
     
    table.setModel(DbUtils.resultSetToTableModel(rs));
   // while(rs.next()) 
    //System.out.println(rs.getInt(1));
    
     
    con.close(); 
     
    }catch(Exception e){ System.out.println(e);} 
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        Labelpic = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Btnupdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LabelBook = new javax.swing.JLabel();
        TxtSlot = new javax.swing.JTextField();
        btnBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Labelpic.setText("Parking Space");
        Labelpic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Slot no.", "Vacant",
            }
        ));
        jScrollPane3.setViewportView(table);

        Btnupdate.setText("Refresh Table");
        Btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Labelpic, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(Btnupdate)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Labelpic, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(Btnupdate)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        LabelBook.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelBook.setText("Enter Slot Number");

        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(LabelBook, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBook)
                            .addComponent(TxtSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LabelBook, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TxtSlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnBook)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        int slotno=Integer.parseInt(TxtSlot.getText());
        
        try {
            if(Selection.getConnection(slotno))
            {
            
            updateldate(na,slotno);          
            Email email=new Email(slotno,na,em);
            //System.out.println("3");
            email.emailSend();
             try{
              outFile(na);
         } catch (IOException ex) 
              {
             System.out.println(ex.getMessage());
         }
           
            JOptionPane.showMessageDialog(null,"Slot booked!!You will recieve a email with the eTicket shortly \n Printable file will open now");
            ProcessBuilder pb = new ProcessBuilder("Notepad.exe", "Ticket.txt");
            pb.start();
           
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Slot already booked!!Please Try a different one");
            }
            System.out.println("Thank you Selection");
        } catch (Exception ex) {
            Logger.getLogger(Selection.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
             System.exit(0);
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void BtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnupdateActionPerformed
        updateTable();
    }//GEN-LAST:event_BtnupdateActionPerformed
public static boolean getConnection(int s) throws Exception{
 try{ 
    Class.forName("com.mysql.jdbc.Driver"); 
     
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root","siddharth"); 
     
    //here sonoo is database name, root is username and password 
     
    Statement stmt=con.createStatement(); 
     
    ResultSet rs=stmt.executeQuery("select * from parking"); 
     
  while(rs.next()) 
  {
  
   if(Integer.parseInt(rs.getString(1))==s)
           {
               if(rs.getNString(2).equals("empty"))
               {
                   String use="in use";
                   String s1=String.valueOf(s);
                   
                   String updateString= "update Parking set Vacant = \""+use+"\" where Slot =\""+s1+"\"";
                                        
                  java.sql.PreparedStatement updateSales = con.prepareStatement(updateString);
                  updateSales.executeUpdate();
                    updateSales.close();
                
             if (updateSales != null) {
            updateSales.close();
                  }
           
                   //con.createStatement().executeQuery("update parking set vacant = \'in use\' where slot = "+String.valueOf(s));
                   System.out.println("5");
                    return true;
               }
               else 
                   return false;
           }
  }  
    con.close(); 
     
    }catch(Exception e){ System.out.println(e);} return false;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //getConnection();
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selection().setVisible(true);
            }
        });
    }

    private void outFile(String n) throws IOException{
        FileWriter fr=new FileWriter("Ticket.txt");
        BufferedWriter br=new BufferedWriter(fr);
        LocalDateTime ldt = LocalDateTime.now();
   System.out.println("Date-"+ldt.getDayOfMonth()+"-"+ldt.getMonth()+"-"+ldt.getYear());
   System.out.println("Time -"+ldt.getHour()+":"+ldt.getMinute()+":"+ldt.getSecond());
        br.write("Parking ticket\n");
        br.write("Name:- "+n+" \n Amount=Rs20 ");
        String date="Date ->"+ldt.getDayOfMonth()+"-"+ldt.getMonth()+"-"+ldt.getYear();
        String time="Time ->"+ldt.getHour()+":"+ldt.getMinute()+":"+ldt.getSecond();
        br.write("\n"+date);
        br.write("\n"+time);
        br.write("\nHave A Nice Day!!");
        br.close();
        fr.close();
        System.out.println("done");
    }

    private void updateldate(String n,int s) {
        
        try{ 
    Class.forName("com.mysql.jdbc.Driver"); 
     
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root","siddharth"); 
     
    //here sonoo is database name, root is username and password 
     
    Statement stmt=con.createStatement(); 
     
    ResultSet rs=stmt.executeQuery("select * from parking"); 
     String updateString
                           = "update login set slot = ? where name = ?";
                   System.out.println("2");
                  java.sql.PreparedStatement updateSales = con.prepareStatement(updateString);
             
                 updateSales.setString(1,String.valueOf(s));
                  updateSales.setString(2,n);
            updateSales.executeUpdate();
                 System.out.println("3");
          
             if (updateSales != null) {
            updateSales.close();
             }
    }catch(Exception e){System.out.println(e.getMessage());}
    
    }
    static class setVisible {

        public setVisible(boolean b) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnupdate;
    private javax.swing.JLabel LabelBook;
    private javax.swing.JLabel Labelpic;
    private javax.swing.JTextField TxtSlot;
    private javax.swing.JButton btnBook;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private final javax.swing.JTable table = new javax.swing.JTable();
    // End of variables declaration//GEN-END:variables
}

 
